<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Autre extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Autre_model');
    } 

    /*
     * Listing of autres
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('autre/index?');
        $config['total_rows'] = $this->Autre_model->get_all_autres_count();
        $this->pagination->initialize($config);

        $data['autres'] = $this->Autre_model->get_all_autres($params);
        
        $data['_view'] = 'autre/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new autre
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('libelleAutre','LibelleAutre','required');
		$this->form_validation->set_rules('typeAutre','TypeAutre','required');
		$this->form_validation->set_rules('idCategories','IdCategories','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'idCategories' => $this->input->post('idCategories'),
				'libelleAutre' => $this->input->post('libelleAutre'),
				'typeAutre' => $this->input->post('typeAutre'),
            );
            
            $autre_id = $this->Autre_model->add_autre($params);
            redirect('autre/index');
        }
        else
        {
			$this->load->model('Category_model');
			$data['all_categories'] = $this->Category_model->get_all_categories();
            
            $data['_view'] = 'autre/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a autre
     */
    function edit($idAutres)
    {   
        // check if the autre exists before trying to edit it
        $data['autre'] = $this->Autre_model->get_autre($idAutres);
        
        if(isset($data['autre']['idAutres']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('libelleAutre','LibelleAutre','required');
			$this->form_validation->set_rules('typeAutre','TypeAutre','required');
			$this->form_validation->set_rules('idCategories','IdCategories','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'idCategories' => $this->input->post('idCategories'),
					'libelleAutre' => $this->input->post('libelleAutre'),
					'typeAutre' => $this->input->post('typeAutre'),
                );

                $this->Autre_model->update_autre($idAutres,$params);            
                redirect('autre/index');
            }
            else
            {
				$this->load->model('Category_model');
				$data['all_categories'] = $this->Category_model->get_all_categories();

                $data['_view'] = 'autre/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The autre you are trying to edit does not exist.');
    } 

    /*
     * Deleting autre
     */
    function remove($idAutres)
    {
        $autre = $this->Autre_model->get_autre($idAutres);

        // check if the autre exists before trying to delete it
        if(isset($autre['idAutres']))
        {
            $this->Autre_model->delete_autre($idAutres);
            redirect('autre/index');
        }
        else
            show_error('The autre you are trying to delete does not exist.');
    }
    
}
