<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Emploi extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Emploi_model');
    } 

    /*
     * Listing of emplois
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('emploi/index?');
        $config['total_rows'] = $this->Emploi_model->get_all_emplois_count();
        $this->pagination->initialize($config);

        $data['emplois'] = $this->Emploi_model->get_all_emplois($params);
        
        $data['_view'] = 'emploi/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new emploi
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('libelleEmploi','LibelleEmploi','required');
		$this->form_validation->set_rules('typeEmploi','TypeEmploi','required');
		$this->form_validation->set_rules('contrat','Contrat','required');
		$this->form_validation->set_rules('idCategories','IdCategories','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'idCategories' => $this->input->post('idCategories'),
				'libelleEmploi' => $this->input->post('libelleEmploi'),
				'typeEmploi' => $this->input->post('typeEmploi'),
				'contrat' => $this->input->post('contrat'),
				'salaire' => $this->input->post('salaire'),
            );
            
            $emploi_id = $this->Emploi_model->add_emploi($params);
            redirect('emploi/index');
        }
        else
        {
			$this->load->model('Category_model');
			$data['all_categories'] = $this->Category_model->get_all_categories();
            
            $data['_view'] = 'emploi/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a emploi
     */
    function edit($idEmplois)
    {   
        // check if the emploi exists before trying to edit it
        $data['emploi'] = $this->Emploi_model->get_emploi($idEmplois);
        
        if(isset($data['emploi']['idEmplois']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('libelleEmploi','LibelleEmploi','required');
			$this->form_validation->set_rules('typeEmploi','TypeEmploi','required');
			$this->form_validation->set_rules('contrat','Contrat','required');
			$this->form_validation->set_rules('idCategories','IdCategories','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'idCategories' => $this->input->post('idCategories'),
					'libelleEmploi' => $this->input->post('libelleEmploi'),
					'typeEmploi' => $this->input->post('typeEmploi'),
					'contrat' => $this->input->post('contrat'),
					'salaire' => $this->input->post('salaire'),
                );

                $this->Emploi_model->update_emploi($idEmplois,$params);            
                redirect('emploi/index');
            }
            else
            {
				$this->load->model('Category_model');
				$data['all_categories'] = $this->Category_model->get_all_categories();

                $data['_view'] = 'emploi/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The emploi you are trying to edit does not exist.');
    } 

    /*
     * Deleting emploi
     */
    function remove($idEmplois)
    {
        $emploi = $this->Emploi_model->get_emploi($idEmplois);

        // check if the emploi exists before trying to delete it
        if(isset($emploi['idEmplois']))
        {
            $this->Emploi_model->delete_emploi($idEmplois);
            redirect('emploi/index');
        }
        else
            show_error('The emploi you are trying to delete does not exist.');
    }
    
}
