<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Immobiliere extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Immobiliere_model');
    } 

    /*
     * Listing of immobilieres
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('immobiliere/index?');
        $config['total_rows'] = $this->Immobiliere_model->get_all_immobilieres_count();
        $this->pagination->initialize($config);

        $data['immobilieres'] = $this->Immobiliere_model->get_all_immobilieres($params);
        
        $data['_view'] = 'immobiliere/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new immobiliere
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('libelleImmo','LibelleImmo','required');
		$this->form_validation->set_rules('typeImmo','TypeImmo','required');
		$this->form_validation->set_rules('idCategories','IdCategories','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'idCategories' => $this->input->post('idCategories'),
				'libelleImmo' => $this->input->post('libelleImmo'),
				'typeImmo' => $this->input->post('typeImmo'),
				'surface' => $this->input->post('surface'),
				'nbrePiece' => $this->input->post('nbrePiece'),
				'ville' => $this->input->post('ville'),
				'region' => $this->input->post('region'),
            );
            
            $immobiliere_id = $this->Immobiliere_model->add_immobiliere($params);
            redirect('immobiliere/index');
        }
        else
        {
			$this->load->model('Category_model');
			$data['all_categories'] = $this->Category_model->get_all_categories();
            
            $data['_view'] = 'immobiliere/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a immobiliere
     */
    function edit($idImmobilieres)
    {   
        // check if the immobiliere exists before trying to edit it
        $data['immobiliere'] = $this->Immobiliere_model->get_immobiliere($idImmobilieres);
        
        if(isset($data['immobiliere']['idImmobilieres']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('libelleImmo','LibelleImmo','required');
			$this->form_validation->set_rules('typeImmo','TypeImmo','required');
			$this->form_validation->set_rules('idCategories','IdCategories','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'idCategories' => $this->input->post('idCategories'),
					'libelleImmo' => $this->input->post('libelleImmo'),
					'typeImmo' => $this->input->post('typeImmo'),
					'surface' => $this->input->post('surface'),
					'nbrePiece' => $this->input->post('nbrePiece'),
					'ville' => $this->input->post('ville'),
					'region' => $this->input->post('region'),
                );

                $this->Immobiliere_model->update_immobiliere($idImmobilieres,$params);            
                redirect('immobiliere/index');
            }
            else
            {
				$this->load->model('Category_model');
				$data['all_categories'] = $this->Category_model->get_all_categories();

                $data['_view'] = 'immobiliere/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The immobiliere you are trying to edit does not exist.');
    } 

    /*
     * Deleting immobiliere
     */
    function remove($idImmobilieres)
    {
        $immobiliere = $this->Immobiliere_model->get_immobiliere($idImmobilieres);

        // check if the immobiliere exists before trying to delete it
        if(isset($immobiliere['idImmobilieres']))
        {
            $this->Immobiliere_model->delete_immobiliere($idImmobilieres);
            redirect('immobiliere/index');
        }
        else
            show_error('The immobiliere you are trying to delete does not exist.');
    }
    
}
