<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Loisir extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Loisir_model');
    } 

    /*
     * Listing of loisirs
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('loisir/index?');
        $config['total_rows'] = $this->Loisir_model->get_all_loisirs_count();
        $this->pagination->initialize($config);

        $data['loisirs'] = $this->Loisir_model->get_all_loisirs($params);
        
        $data['_view'] = 'loisir/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new loisir
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('libelleLoisir','LibelleLoisir','required');
		$this->form_validation->set_rules('idCategories','IdCategories','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'idCategories' => $this->input->post('idCategories'),
				'libelleLoisir' => $this->input->post('libelleLoisir'),
            );
            
            $loisir_id = $this->Loisir_model->add_loisir($params);
            redirect('loisir/index');
        }
        else
        {
			$this->load->model('Category_model');
			$data['all_categories'] = $this->Category_model->get_all_categories();
            
            $data['_view'] = 'loisir/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a loisir
     */
    function edit($idLoisirs)
    {   
        // check if the loisir exists before trying to edit it
        $data['loisir'] = $this->Loisir_model->get_loisir($idLoisirs);
        
        if(isset($data['loisir']['idLoisirs']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('libelleLoisir','LibelleLoisir','required');
			$this->form_validation->set_rules('idCategories','IdCategories','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'idCategories' => $this->input->post('idCategories'),
					'libelleLoisir' => $this->input->post('libelleLoisir'),
                );

                $this->Loisir_model->update_loisir($idLoisirs,$params);            
                redirect('loisir/index');
            }
            else
            {
				$this->load->model('Category_model');
				$data['all_categories'] = $this->Category_model->get_all_categories();

                $data['_view'] = 'loisir/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The loisir you are trying to edit does not exist.');
    } 

    /*
     * Deleting loisir
     */
    function remove($idLoisirs)
    {
        $loisir = $this->Loisir_model->get_loisir($idLoisirs);

        // check if the loisir exists before trying to delete it
        if(isset($loisir['idLoisirs']))
        {
            $this->Loisir_model->delete_loisir($idLoisirs);
            redirect('loisir/index');
        }
        else
            show_error('The loisir you are trying to delete does not exist.');
    }
    
}
