<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Service extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Service_model');
    } 

    /*
     * Listing of services
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('service/index?');
        $config['total_rows'] = $this->Service_model->get_all_services_count();
        $this->pagination->initialize($config);

        $data['services'] = $this->Service_model->get_all_services($params);
        
        $data['_view'] = 'service/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new service
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('libelleService','LibelleService','required');
		$this->form_validation->set_rules('idCategories','IdCategories','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'idCategories' => $this->input->post('idCategories'),
				'libelleService' => $this->input->post('libelleService'),
            );
            
            $service_id = $this->Service_model->add_service($params);
            redirect('service/index');
        }
        else
        {
			$this->load->model('Category_model');
			$data['all_categories'] = $this->Category_model->get_all_categories();
            
            $data['_view'] = 'service/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a service
     */
    function edit($idServices)
    {   
        // check if the service exists before trying to edit it
        $data['service'] = $this->Service_model->get_service($idServices);
        
        if(isset($data['service']['idServices']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('libelleService','LibelleService','required');
			$this->form_validation->set_rules('idCategories','IdCategories','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'idCategories' => $this->input->post('idCategories'),
					'libelleService' => $this->input->post('libelleService'),
                );

                $this->Service_model->update_service($idServices,$params);            
                redirect('service/index');
            }
            else
            {
				$this->load->model('Category_model');
				$data['all_categories'] = $this->Category_model->get_all_categories();

                $data['_view'] = 'service/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The service you are trying to edit does not exist.');
    } 

    /*
     * Deleting service
     */
    function remove($idServices)
    {
        $service = $this->Service_model->get_service($idServices);

        // check if the service exists before trying to delete it
        if(isset($service['idServices']))
        {
            $this->Service_model->delete_service($idServices);
            redirect('service/index');
        }
        else
            show_error('The service you are trying to delete does not exist.');
    }
    
}
