<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Typeannonce extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Typeannonce_model');
    } 

    /*
     * Listing of typeannonce
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('typeannonce/index?');
        $config['total_rows'] = $this->Typeannonce_model->get_all_typeannonce_count();
        $this->pagination->initialize($config);

        $data['typeannonce'] = $this->Typeannonce_model->get_all_typeannonce($params);
        
        $data['_view'] = 'typeannonce/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new typeannonce
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('type','Type','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'type' => $this->input->post('type'),
            );
            
            $typeannonce_id = $this->Typeannonce_model->add_typeannonce($params);
            redirect('typeannonce/index');
        }
        else
        {            
            $data['_view'] = 'typeannonce/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a typeannonce
     */
    function edit($idTypeAnnonce)
    {   
        // check if the typeannonce exists before trying to edit it
        $data['typeannonce'] = $this->Typeannonce_model->get_typeannonce($idTypeAnnonce);
        
        if(isset($data['typeannonce']['idTypeAnnonce']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('type','Type','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'type' => $this->input->post('type'),
                );

                $this->Typeannonce_model->update_typeannonce($idTypeAnnonce,$params);            
                redirect('typeannonce/index');
            }
            else
            {
                $data['_view'] = 'typeannonce/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The typeannonce you are trying to edit does not exist.');
    } 

    /*
     * Deleting typeannonce
     */
    function remove($idTypeAnnonce)
    {
        $typeannonce = $this->Typeannonce_model->get_typeannonce($idTypeAnnonce);

        // check if the typeannonce exists before trying to delete it
        if(isset($typeannonce['idTypeAnnonce']))
        {
            $this->Typeannonce_model->delete_typeannonce($idTypeAnnonce);
            redirect('typeannonce/index');
        }
        else
            show_error('The typeannonce you are trying to delete does not exist.');
    }
    
}
