<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Typeutilisateur extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Typeutilisateur_model');
    } 

    /*
     * Listing of typeutilisateur
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('typeutilisateur/index?');
        $config['total_rows'] = $this->Typeutilisateur_model->get_all_typeutilisateur_count();
        $this->pagination->initialize($config);

        $data['typeutilisateur'] = $this->Typeutilisateur_model->get_all_typeutilisateur($params);
        
        $data['_view'] = 'typeutilisateur/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new typeutilisateur
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('type','Type','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'type' => $this->input->post('type'),
            );
            
            $typeutilisateur_id = $this->Typeutilisateur_model->add_typeutilisateur($params);
            redirect('typeutilisateur/index');
        }
        else
        {            
            $data['_view'] = 'typeutilisateur/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a typeutilisateur
     */
    function edit($idTypeUtilisateur)
    {   
        // check if the typeutilisateur exists before trying to edit it
        $data['typeutilisateur'] = $this->Typeutilisateur_model->get_typeutilisateur($idTypeUtilisateur);
        
        if(isset($data['typeutilisateur']['idTypeUtilisateur']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('type','Type','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'type' => $this->input->post('type'),
                );

                $this->Typeutilisateur_model->update_typeutilisateur($idTypeUtilisateur,$params);            
                redirect('typeutilisateur/index');
            }
            else
            {
                $data['_view'] = 'typeutilisateur/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The typeutilisateur you are trying to edit does not exist.');
    } 

    /*
     * Deleting typeutilisateur
     */
    function remove($idTypeUtilisateur)
    {
        $typeutilisateur = $this->Typeutilisateur_model->get_typeutilisateur($idTypeUtilisateur);

        // check if the typeutilisateur exists before trying to delete it
        if(isset($typeutilisateur['idTypeUtilisateur']))
        {
            $this->Typeutilisateur_model->delete_typeutilisateur($idTypeUtilisateur);
            redirect('typeutilisateur/index');
        }
        else
            show_error('The typeutilisateur you are trying to delete does not exist.');
    }
    
}
