<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Utilisateur extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Utilisateur_model');
    } 

    /*
     * Listing of utilisateurs
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('utilisateur/index?');
        $config['total_rows'] = $this->Utilisateur_model->get_all_utilisateurs_count();
        $this->pagination->initialize($config);

        $data['utilisateurs'] = $this->Utilisateur_model->get_all_utilisateurs($params);
        
        $data['_view'] = 'utilisateur/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new utilisateur
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('password','Password','required|alpha_numeric|min_length[8]');
		$this->form_validation->set_rules('nom','Nom','required');
		$this->form_validation->set_rules('prenom','Prenom','required');
		$this->form_validation->set_rules('email','Email','required|valid_email');
		$this->form_validation->set_rules('telephone','Telephone','required');
		$this->form_validation->set_rules('idTypeUtilisateur','IdTypeUtilisateur','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'idTypeUtilisateur' => $this->input->post('idTypeUtilisateur'),
				'password' => $this->input->post('password'),
				'nom' => $this->input->post('nom'),
				'prenom' => $this->input->post('prenom'),
				'email' => $this->input->post('email'),
				'telephone' => $this->input->post('telephone'),
            );
            
            $utilisateur_id = $this->Utilisateur_model->add_utilisateur($params);
            redirect('utilisateur/index');
        }
        else
        {
			$this->load->model('Typeutilisateur_model');
			$data['all_typeutilisateur'] = $this->Typeutilisateur_model->get_all_typeutilisateur();
            
            $data['_view'] = 'utilisateur/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a utilisateur
     */
    function edit($idUtilisateurs)
    {   
        // check if the utilisateur exists before trying to edit it
        $data['utilisateur'] = $this->Utilisateur_model->get_utilisateur($idUtilisateurs);
        
        if(isset($data['utilisateur']['idUtilisateurs']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('password','Password','required|alpha_numeric|min_length[8]');
			$this->form_validation->set_rules('nom','Nom','required');
			$this->form_validation->set_rules('prenom','Prenom','required');
			$this->form_validation->set_rules('email','Email','required|valid_email');
			$this->form_validation->set_rules('telephone','Telephone','required');
			$this->form_validation->set_rules('idTypeUtilisateur','IdTypeUtilisateur','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'idTypeUtilisateur' => $this->input->post('idTypeUtilisateur'),
					'password' => $this->input->post('password'),
					'nom' => $this->input->post('nom'),
					'prenom' => $this->input->post('prenom'),
					'email' => $this->input->post('email'),
					'telephone' => $this->input->post('telephone'),
                );

                $this->Utilisateur_model->update_utilisateur($idUtilisateurs,$params);            
                redirect('utilisateur/index');
            }
            else
            {
				$this->load->model('Typeutilisateur_model');
				$data['all_typeutilisateur'] = $this->Typeutilisateur_model->get_all_typeutilisateur();

                $data['_view'] = 'utilisateur/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The utilisateur you are trying to edit does not exist.');
    } 

    /*
     * Deleting utilisateur
     */
    function remove($idUtilisateurs)
    {
        $utilisateur = $this->Utilisateur_model->get_utilisateur($idUtilisateurs);

        // check if the utilisateur exists before trying to delete it
        if(isset($utilisateur['idUtilisateurs']))
        {
            $this->Utilisateur_model->delete_utilisateur($idUtilisateurs);
            redirect('utilisateur/index');
        }
        else
            show_error('The utilisateur you are trying to delete does not exist.');
    }
    
}
