<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Annonce_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get annonce by idannonces
     */
    function get_annonce($idannonces)
    {
        return $this->db->get_where('Annonces',array('idannonces'=>$idannonces))->row_array();
    }
    
    /*
     * Get all annonces count
     */
    function get_all_annonces_count()
    {
        $this->db->from('Annonces');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all annonces
     */
    function get_all_annonces($params = array())
    {
        $this->db->order_by('idannonces', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('Annonces')->result_array();
    }
        
    /*
     * function to add new annonce
     */
    function add_annonce($params)
    {
        $this->db->insert('Annonces',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update annonce
     */
    function update_annonce($idannonces,$params)
    {
        $this->db->where('idannonces',$idannonces);
        return $this->db->update('Annonces',$params);
    }
    
    /*
     * function to delete annonce
     */
    function delete_annonce($idannonces)
    {
        return $this->db->delete('Annonces',array('idannonces'=>$idannonces));
    }
}
