<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Autre_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get autre by idAutres
     */
    function get_autre($idAutres)
    {
        return $this->db->get_where('Autres',array('idAutres'=>$idAutres))->row_array();
    }
    
    /*
     * Get all autres count
     */
    function get_all_autres_count()
    {
        $this->db->from('Autres');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all autres
     */
    function get_all_autres($params = array())
    {
        $this->db->order_by('idAutres', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('Autres')->result_array();
    }
        
    /*
     * function to add new autre
     */
    function add_autre($params)
    {
        $this->db->insert('Autres',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update autre
     */
    function update_autre($idAutres,$params)
    {
        $this->db->where('idAutres',$idAutres);
        return $this->db->update('Autres',$params);
    }
    
    /*
     * function to delete autre
     */
    function delete_autre($idAutres)
    {
        return $this->db->delete('Autres',array('idAutres'=>$idAutres));
    }
}
