<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bienetre_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bienetre by idBienEtre
     */
    function get_bienetre($idBienEtre)
    {
        return $this->db->get_where('BienEtre',array('idBienEtre'=>$idBienEtre))->row_array();
    }
    
    /*
     * Get all bienetre count
     */
    function get_all_bienetre_count()
    {
        $this->db->from('BienEtre');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all bienetre
     */
    function get_all_bienetre($params = array())
    {
        $this->db->order_by('idBienEtre', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('BienEtre')->result_array();
    }
        
    /*
     * function to add new bienetre
     */
    function add_bienetre($params)
    {
        $this->db->insert('BienEtre',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bienetre
     */
    function update_bienetre($idBienEtre,$params)
    {
        $this->db->where('idBienEtre',$idBienEtre);
        return $this->db->update('BienEtre',$params);
    }
    
    /*
     * function to delete bienetre
     */
    function delete_bienetre($idBienEtre)
    {
        return $this->db->delete('BienEtre',array('idBienEtre'=>$idBienEtre));
    }
}
