<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Category_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get category by idCategories
     */
    function get_category($idCategories)
    {
        return $this->db->get_where('Categories',array('idCategories'=>$idCategories))->row_array();
    }
    
    /*
     * Get all categories count
     */
    function get_all_categories_count()
    {
        $this->db->from('Categories');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all categories
     */
    function get_all_categories($params = array())
    {
        $this->db->order_by('idCategories', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('Categories')->result_array();
    }
        
    /*
     * function to add new category
     */
    function add_category($params)
    {
        $this->db->insert('Categories',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update category
     */
    function update_category($idCategories,$params)
    {
        $this->db->where('idCategories',$idCategories);
        return $this->db->update('Categories',$params);
    }
    
    /*
     * function to delete category
     */
    function delete_category($idCategories)
    {
        return $this->db->delete('Categories',array('idCategories'=>$idCategories));
    }
}
