<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Emploi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get emploi by idEmplois
     */
    function get_emploi($idEmplois)
    {
        return $this->db->get_where('Emplois',array('idEmplois'=>$idEmplois))->row_array();
    }
    
    /*
     * Get all emplois count
     */
    function get_all_emplois_count()
    {
        $this->db->from('Emplois');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all emplois
     */
    function get_all_emplois($params = array())
    {
        $this->db->order_by('idEmplois', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('Emplois')->result_array();
    }
        
    /*
     * function to add new emploi
     */
    function add_emploi($params)
    {
        $this->db->insert('Emplois',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update emploi
     */
    function update_emploi($idEmplois,$params)
    {
        $this->db->where('idEmplois',$idEmplois);
        return $this->db->update('Emplois',$params);
    }
    
    /*
     * function to delete emploi
     */
    function delete_emploi($idEmplois)
    {
        return $this->db->delete('Emplois',array('idEmplois'=>$idEmplois));
    }
}
