<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Image_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get image by idImages
     */
    function get_image($idImages)
    {
        return $this->db->get_where('Images',array('idImages'=>$idImages))->row_array();
    }
    
    /*
     * Get all images count
     */
    function get_all_images_count()
    {
        $this->db->from('Images');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all images
     */
    function get_all_images($params = array())
    {
        $this->db->order_by('idImages', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('Images')->result_array();
    }
        
    /*
     * function to add new image
     */
    function add_image($params)
    {
        $this->db->insert('Images',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update image
     */
    function update_image($idImages,$params)
    {
        $this->db->where('idImages',$idImages);
        return $this->db->update('Images',$params);
    }
    
    /*
     * function to delete image
     */
    function delete_image($idImages)
    {
        return $this->db->delete('Images',array('idImages'=>$idImages));
    }
}
