<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Immobiliere_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get immobiliere by idImmobilieres
     */
    function get_immobiliere($idImmobilieres)
    {
        return $this->db->get_where('Immobilieres',array('idImmobilieres'=>$idImmobilieres))->row_array();
    }
    
    /*
     * Get all immobilieres count
     */
    function get_all_immobilieres_count()
    {
        $this->db->from('Immobilieres');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all immobilieres
     */
    function get_all_immobilieres($params = array())
    {
        $this->db->order_by('idImmobilieres', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('Immobilieres')->result_array();
    }
        
    /*
     * function to add new immobiliere
     */
    function add_immobiliere($params)
    {
        $this->db->insert('Immobilieres',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update immobiliere
     */
    function update_immobiliere($idImmobilieres,$params)
    {
        $this->db->where('idImmobilieres',$idImmobilieres);
        return $this->db->update('Immobilieres',$params);
    }
    
    /*
     * function to delete immobiliere
     */
    function delete_immobiliere($idImmobilieres)
    {
        return $this->db->delete('Immobilieres',array('idImmobilieres'=>$idImmobilieres));
    }
}
