<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Loisir_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get loisir by idLoisirs
     */
    function get_loisir($idLoisirs)
    {
        return $this->db->get_where('Loisirs',array('idLoisirs'=>$idLoisirs))->row_array();
    }
    
    /*
     * Get all loisirs count
     */
    function get_all_loisirs_count()
    {
        $this->db->from('Loisirs');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all loisirs
     */
    function get_all_loisirs($params = array())
    {
        $this->db->order_by('idLoisirs', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('Loisirs')->result_array();
    }
        
    /*
     * function to add new loisir
     */
    function add_loisir($params)
    {
        $this->db->insert('Loisirs',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update loisir
     */
    function update_loisir($idLoisirs,$params)
    {
        $this->db->where('idLoisirs',$idLoisirs);
        return $this->db->update('Loisirs',$params);
    }
    
    /*
     * function to delete loisir
     */
    function delete_loisir($idLoisirs)
    {
        return $this->db->delete('Loisirs',array('idLoisirs'=>$idLoisirs));
    }
}
