<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Typeutilisateur_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get typeutilisateur by idTypeUtilisateur
     */
    function get_typeutilisateur($idTypeUtilisateur)
    {
        return $this->db->get_where('TypeUtilisateur',array('idTypeUtilisateur'=>$idTypeUtilisateur))->row_array();
    }
    
    /*
     * Get all typeutilisateur count
     */
    function get_all_typeutilisateur_count()
    {
        $this->db->from('TypeUtilisateur');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all typeutilisateur
     */
    function get_all_typeutilisateur($params = array())
    {
        $this->db->order_by('idTypeUtilisateur', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('TypeUtilisateur')->result_array();
    }
        
    /*
     * function to add new typeutilisateur
     */
    function add_typeutilisateur($params)
    {
        $this->db->insert('TypeUtilisateur',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update typeutilisateur
     */
    function update_typeutilisateur($idTypeUtilisateur,$params)
    {
        $this->db->where('idTypeUtilisateur',$idTypeUtilisateur);
        return $this->db->update('TypeUtilisateur',$params);
    }
    
    /*
     * function to delete typeutilisateur
     */
    function delete_typeutilisateur($idTypeUtilisateur)
    {
        return $this->db->delete('TypeUtilisateur',array('idTypeUtilisateur'=>$idTypeUtilisateur));
    }
}
