<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Vehicule_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get vehicule by idVehicules
     */
    function get_vehicule($idVehicules)
    {
        return $this->db->get_where('Vehicules',array('idVehicules'=>$idVehicules))->row_array();
    }
    
    /*
     * Get all vehicules count
     */
    function get_all_vehicules_count()
    {
        $this->db->from('Vehicules');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all vehicules
     */
    function get_all_vehicules($params = array())
    {
        $this->db->order_by('idVehicules', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('Vehicules')->result_array();
    }
        
    /*
     * function to add new vehicule
     */
    function add_vehicule($params)
    {
        $this->db->insert('Vehicules',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update vehicule
     */
    function update_vehicule($idVehicules,$params)
    {
        $this->db->where('idVehicules',$idVehicules);
        return $this->db->update('Vehicules',$params);
    }
    
    /*
     * function to delete vehicule
     */
    function delete_vehicule($idVehicules)
    {
        return $this->db->delete('Vehicules',array('idVehicules'=>$idVehicules));
    }
}
